    pc: {
      h1: "De qué se trata",
      p1: "Durante los últimos cinco años, ha ocurrido un cambio silencioso en paid social: <strong>los algoritmos pueden segmentar mejor que cualquier humano.</strong> Meta, TikTok y Google ahora distribuyen los presupuestos en gran medida de forma automática. Lo que no pueden inventar por ti es la imagen, el gancho, los dos segundos que detienen el pulgar.",
      p2: "Es exactamente por eso que el creativo es la palanca decisiva hoy en día. Estudios de datos internos de Meta y auditores de rendimiento independientes atribuyen sistemáticamente <strong>hasta el 70 por ciento del éxito de una campaña</strong> al creativo. Segmentación, pujas, ubicaciones — todo importante, pero cada vez más una commodity. El creativo es el espacio de diferenciación que te queda.",
      p3: "Performance creative es la disciplina de tomarse este conocimiento en serio.",
      imgAlt1: "Flujo de trabajo de producción creativa — Cámara de alta gama y pantallas digitales",
      imgCaption1: "Flujo de trabajo creativo: desde el brief hasta el asset probado",
      h2: "Definición: qué es el performance creative — y qué no es",
      p4: "Hay tres conceptos erróneos comunes que encontramos a diario:",
      mis1: "<strong>1. \"Imágenes hermosas = buenos creativos.\"</strong><br />Incorrecto. Una foto editorial técnicamente perfecta puede pasar desapercibida en Instagram Stories porque no tiene un gancho (hook) en los primeros 1,5 segundos. El performance creative no comienza con la estética — comienza con la pregunta: <em>¿Por qué alguien se detendría en este encuadre?</em>",
      mis2: "<strong>2. \"Simplemente probamos más variantes.\"</strong><br />Más variantes sin una hipótesis es ruido. El performance creative trabaja con hipótesis claras por variante: <em>esta versión prueba el Gancho A contra el Gancho B</em>; <em>esta prueba el formato vertical frente al cuadrado</em>; <em>esta prueba problema-solución frente a aspiracional</em>.",
      mis3: "<strong>3. \"El algoritmo lo maneja automáticamente.\"</strong><br />El algoritmo es bueno para encontrar el mejor de tus creativos. Es malo para inventar creativos que no has producido. Si tu pool creativo contiene tres variantes, optimiza para la mejor de las tres — incluso si las tres son mediocres.",
      h3: "La mecánica: fatiga creativa",
      p5: "Cada creativo tiene una vida útil. Una regla general aproximada de nuestra práctica:",
      tableH1: "Gasto publicitario mensual",
      tableH2: "Vida útil típica del creativo",
      tableRows: [
        { spend: "€5–15k", halflife: "4–8 semanas" },
        { spend: "€15–50k", halflife: "2–4 semanas" },
        { spend: "€50–150k", halflife: "1–3 semanas" },
        { spend: "€150k+", halflife: "unos pocos días a 2 semanas" },
      ],
      p6: "Cuanto mayor sea tu presupuesto, más rápido verá la misma audiencia el mismo creativo. Los límites de frecuencia (frequency caps) retrasan el efecto pero no lo solucionan. La implicación: <strong>cualquiera que quiera escalar necesita un pipeline creativo continuo.</strong> No una macro sesión por trimestre, sino un ritmo de variantes frescas y probadas cada 2–4 semanas.",
      imgAlt2: "Panel de datos de métricas publicitarias — Seguimiento de rendimiento en tiempo real",
      imgCaption2: "KPIs en tiempo real: tasa de gancho (hook rate), CTR, CPC, ROAS",
      h4: "Los KPIs que realmente importan",
      p7: "Hay demasiadas métricas en una cuenta publicitaria. Para el performance creative, estas cuatro son centrales:",
      kpi1: "<strong>Tasa de gancho (Hook rate) / Tasa de visualización de 3 segundos</strong> — ¿cuántas personas se detienen en absoluto? Esta es la evaluación más honesta de tu creativo, independiente de la landing page.",
      kpi2: "<strong>CTR (tasa de clics) / CTR saliente</strong> — ¿cuántos hacen clic? Esto revela si la promesa en el creativo coincide con la expectativa del clic.",
      kpi3: "<strong>CPC (coste por clic)</strong> — misma información, escalada de manera diferente. Cuando baja, tu creativo se está volviendo más eficiente.",
      kpi4: "<strong>ROAS / CAC</strong> — la métrica de negocio. Combina creativo, funnel y producto. Un creativo que reduce el CTR pero aumenta el CAC no es un buen creativo.",
      p8: "Reportamos los cuatro — y sobre todo su <em>cambio relativo</em> entre el creativo de control y el de prueba. Los números absolutos sin comparación son teatro de marketing.",
      h5: "Qué hace diferente a Belleza / Salud / Estilo de vida",
      p9: "Tres cosas que distinguen a esta industria del SaaS, viajes o moda:",
      spec1: "<strong>Peso visual.</strong> En belleza, compras lo que ves. Texturas, tonos de piel, iluminación — pequeños detalles que pueden arruinarse en postproducción son relevantes para la conversión aquí.",
      spec2: "<strong>Cumplimiento de claims.</strong> Las marcas de salud operan en un entorno publicitario regulado (HWG, Reglamento de Cosméticos). Los creativos deben rendir sin hacer afirmaciones no permitidas — una disciplina creativa que requiere conocimiento específico de la industria.",
      spec3: "<strong>Identificación &gt; aspiración.</strong> TikTok ha cambiado el juego: los compradores de belleza de hoy quieren ver personas que se parezcan a ellos, no modelos inalcanzables. Los creativos publicitarios que no siguen esta línea son ignorados.",
      h6: "Cómo Mirrou produce performance creative",
      p10Before: "No producimos creativos individuales. Ejecutamos un",
      p10Link: "Creative Engine",
      p10After: "— un bucle de cinco pasos que hace sistemático el output creativo: análisis, hipótesis, producción, testing, aprendizaje.",
      p11Before: "El setup híbrido (",
      p11Link: "Foto + Fondo de IA",
      p11After: ") nos permite entregar treinta variantes en el mismo tiempo que un estudio convencional produce tres imágenes — sin pérdida de calidad, y sin imágenes de IA que minen la confianza a través de la suavidad algorítmica.",
      imgAlt3: "Sesión de Estrategia de Equipo — Fotografía Editorial Oscura",
      imgCaption3: "Sesión de estrategia: hipótesis antes de la producción",
      h7: "Lo que puedes hacer a continuación",
      p12: "Si tu marca gasta entre €10k y €150k por mes en paid social y sientes que tus creativos no se renuevan con la frecuencia necesaria, tres palancas son realistas:",
      act1: "<strong>Audita tu pool creativo.</strong> ¿Cuántas variantes estuvieron activas en los últimos 30 días? ¿Cuántas de ellas se probaron realmente entre sí?",
      act2: "<strong>Auditoría de ganchos (hooks).</strong> ¿Los primeros 1,5 segundos de tus creativos de mayor gasto están diseñados deliberadamente — o surgieron por casualidad?",
      act3: "<strong>Introduce un registro de aprendizaje (learning log).</strong> ¿Qué hipótesis se probó contra cuál, cuándo y con qué resultado? Si no puedes responder a esta pregunta en 60 segundos, te estás perdiendo el bucle de aprendizaje.",
      p13Before: "Ayudamos con los tres. En una",
      p13Link: "llamada estratégica",
      p13After: "obtienes una evaluación honesta en 30 minutos — sin coste, sin presión comercial.",
    },
    ce: {
      h1: "Por qué un 'sistema operativo'",
      p1: "La mayoría de los briefs de agencia funcionan de forma lineal: entra el brief, sale la sesión fotográfica, llega la factura. Eso está bien si necesitas una campaña una vez por trimestre. No está bien cuando tu cuenta publicitaria funciona las 24 horas y necesita creativos frescos y probados cada pocas semanas.",
      p2: "Lo que necesitas no es otra sesión. Necesitas un <strong>bucle que no se detenga</strong>. Lo llamamos el Creative Engine.",
      h2: "Los cinco pasos",
      h3a: "01 — Análisis",
      p3: "Obtenemos acceso de solo lectura a tu cuenta publicitaria (Meta, TikTok, Google Ads). Leemos los últimos 60–90 días:",
      anal1: "¿Qué creativos han estado gastando, cuáles se han fatigado?",
      anal2: "¿Dónde cae la tasa de gancho (hook rate)? ¿Dónde cae el CTR?",
      anal3: "¿Qué ganchos, formatos y mundos visuales se correlacionan con un buen ROAS — y cuáles solo con un buen CTR (no son lo mismo)?",
      p4: "El resultado de este paso es un documento de auditoría creativa. No es material de marketing, sino un inventario honesto. Forma la base de todo lo que sigue.",
      h3b: "02 — Hipótesis",
      p5: "Del análisis derivamos hipótesis creativas concretas. Una hipótesis no es 'probemos algo nuevo'. Una hipótesis tiene este formato:",
      bq1: "Sospechamos que <strong>[variante creativa específica]</strong> para <strong>[público objetivo específico]</strong> conducirá a <strong>[efecto KPI específico]</strong> — porque <strong>[razonamiento basado en datos o en la observación del mercado]</strong>.",
      p6: "Ejemplo:",
      bq2: "Sospechamos que una variante de gancho con el punto de dolor 'protector solar pegajoso' logrará una tasa de gancho al menos un 25% mayor que la variante aspiracional actual — porque las 3 principales publicaciones orgánicas en TikTok de nuestro competidor utilizan la misma apertura de punto de dolor.",
      p7: "Por ciclo de producción solemos formular 3–5 hipótesis. Cada una se enfrenta al mejor creativo actual mediante celdas de prueba (control + 2–3 variantes).",
      h3c: "03 — Producción",
      p8Before: "La producción es híbrida. Combinamos fotografía real de nuestro estudio de Hamburgo con fondos generados por IA y variantes de estilo (",
      p8Link: "más aquí",
      p8After: "). De un solo día de rodaje, surgen 20–40 creativos finales — no 5.",
      p9: "Esto no es un fin en sí mismo. Es la única forma de entregar celdas de prueba reales con suficiente profundidad de variantes en un ritmo de 2 semanas. Cada variante recibe un nombre de archivo claro y un ID de hipótesis.",
      h3d: "04 — Pruebas (Testing)",
      p10: "Las pruebas se configuran de forma estructurada. Lógica estándar:",
      test1: "1 hipótesis = 1 prueba",
      test2: "1 prueba = al menos 2 celdas (control + variante)",
      test3: "Estadística mínima: a partir de 1.000 clics o 50.000 impresiones por celda",
      test4: "Regla de parada: después de 7 días, o cuando una celda tiene un rendimiento significativamente inferior",
      p11: "Utilizamos las funciones de pruebas A/B de las plataformas, complementadas con nuestras propias estructuras UTM. Los informes son semanales.",
      h3e: "05 — Aprendizaje",
      p12: "Este es el paso que casi todos omiten — y el que marca la diferencia entre el rendimiento y una curva de aprendizaje real. Cada evaluación de prueba se almacena en un registro de aprendizaje con:",
      learn1: "Hipótesis (formulada antes de la prueba)",
      learn2: "Configuración de la prueba",
      learn3: "Resultado (hipótesis ganada/perdida, con delta de KPI)",
      learn4: "Insight generalizable: <em>¿qué aprendemos para futuros creativos?</em>",
      learn5: "Próxima prueba (lo que examinaremos a continuación en base a este resultado)",
      p13: "Después de 6 meses, no solo has producido más de 30 creativos. Tienes una ruta de aprendizaje documentada: <em>¿qué ganchos funcionan en tu nicho?</em> Este conocimiento perdura más allá de cualquier creativo individual.",
      h4: "Aislamiento de variables: ciencia, no adivinanzas",
      p14: "El mayor error en las pruebas creativas: cambiar tres cosas a la vez. Si la nueva variante gana, no sabes qué lo causó. Nuestra regla: <strong>una variable por prueba</strong>. Gancho contra gancho. Formato contra formato. Pero nunca todo a la vez.",
      h5: "Cómo funciona el bucle en la práctica",
      p15: "En el modelo de iguala (retainer), el bucle se ejecuta continuamente:",
      loop1: "<strong>Semana 1–2:</strong> Análisis + hipótesis + actualización del brief",
      loop2: "<strong>Semana 3:</strong> Día de rodaje en Hamburgo",
      loop3: "<strong>Semana 4:</strong> Postproducción + variantes de IA + configuración de la prueba",
      loop4: "<strong>Semana 5–6:</strong> Pruebas en curso, informes, actualización de aprendizaje",
      loop5: "El bucle se reinicia",
      p16: "Para clientes Tier S (gasto publicitario de €10–30k / mes), el bucle es de unas 6 semanas; para clientes Tier L (€80k+), de unas 3 semanas. La lógica sigue siendo la misma.",
      h6: "Lo que el motor no es",
      p17: "No es una herramienta, no es un SaaS, no es una palabra de moda. Es una disciplina: un conjunto de prácticas que evita que la producción creativa se convierta en algo instintivo. Nada más, nada menos.",
      p18Before: "Más en los artículos del clúster a continuación — y en una demostración detallada de nuestra metodología en el",
      p18Link: "caso piloto",
      p18After: ".",
    },
    be: {
      h1: "El mercado: grande, en crecimiento, competitivo",
      p1: "Alemania es el mayor mercado de belleza y cuidado personal de Europa con un volumen de alrededor de 35.600 millones de euros (2025) y una cuota online de más del 21% — con tendencia al alza. A nivel mundial, el mercado de la belleza creció a un ritmo de dos dígitos recientemente, con el e-commerce expandiéndose seis veces más rápido que el comercio físico. Sólo TikTok Shop ya representa alrededor del 22% de las compras de comercio social (social commerce) en todo el mundo.",
      p2: "¿Qué significa eso? <strong>La atención del comprador se está desplazando definitivamente a los feeds y stories.</strong> Las marcas que no están presentes con creativos de alta calidad y optimizados para el rendimiento están perdiendo cuota de mercado — no a lo largo de años, sino de trimestres.",
      p3: "Al mismo tiempo, la competencia se intensifica: los CPMs y CPCs están subiendo a medida que más marcas D2C compiten por la misma audiencia. Quien quiera crecer en este entorno tiene dos opciones: más presupuesto o mejores creativos. Más presupuesto tiene un límite en algún momento. Mejores creativos, no.",
      h2: "Qué hace especiales a las marcas de Belleza / Salud / Estilo de vida",
      h3a: "Peso visual",
      p4: "En belleza, compras lo que ves — literalmente. Texturas, tonos de piel, reflejos de luz, brillo labial. Estos micro-señales deciden en TikTok en 1,5 segundos si alguien se detiene o sigue deslizando. Una foto de base de maquillaje mal iluminada arruina la conversión de todo un funnel — por muy buena que sea la segmentación.",
      h3b: "El cumplimiento no es una ocurrencia tardía",
      p5: "Las marcas de salud y belleza operan en un entorno publicitario regulado:",
      comp1: "<strong>Heilmittelwerbegesetz (HWG)</strong> para productos con declaraciones de eficacia",
      comp2: "<strong>Reglamento de Cosméticos (CE) Nº 1223/2009</strong> para declaraciones de ingredientes",
      comp3: "<strong>Directrices publicitarias de la UE</strong> sobre publicidad comparativa y manipulación de imágenes",
      comp4: "a partir de 2026: <strong>Ley de IA de la UE</strong> para visuales generados por IA (obligación de etiquetado)",
      p6: "Los creativos deben rendir sin hacer afirmaciones no permitidas. Un equipo creativo que no conoce estas líneas produce publicidad sin fuerza o riesgos legales. Nos hemos especializado deliberadamente en esta industria para evitar ambos.",
      h3c: "El cambio hacia la identificación",
      p7: "TikTok ha puesto patas arriba el marketing de belleza: el comprador ya no quiere ver a una modelo perfectamente retocada, sino a alguien que se parezca a él — con los mismos problemas de piel, la misma rutina, el mismo escepticismo. Los visuales aspiracionales todavía funcionan, pero ya no como configuración predeterminada.",
      p8: "Como resultado, las estrategias creativas exitosas han cambiado: lejos del 'así es como se ve el producto en su mejor momento', hacia el 'así es como funciona el producto en la vida real cotidiana'. Esto tiene implicaciones para el set, el casting, la iluminación, la postproducción — y para la pregunta de qué es siquiera un 'buen' creativo de belleza.",
      h3d: "La frecuencia supera a la perfección",
      p9Before: "Las campañas de belleza tradicionales se producían dos veces al año y luego se lanzaban. Hoy en día, una marca D2C con €30k de gasto mensual necesita aproximadamente <strong>20–40 creativos nuevos al mes</strong> para evitar la fatiga creativa. Este número es físicamente inalcanzable si cada imagen tiene un día completo de rodaje. Las configuraciones híbridas (",
      p9Link: "Foto + Fondo de IA + Variantes de IA",
      p9After: ") no son una tendencia aquí — son un requisito previo.",
      h4: "Comparación de canales: Meta vs. TikTok para belleza",
      p10: "Un creativo para Instagram rara vez funciona igual en TikTok. Mientras que los usuarios de Meta están acostumbrados a una cierta 'estética pulida', TikTok exige un lenguaje más crudo y rápido. Diseñamos creativos <strong>pensando primero en el canal (channel-first)</strong>: características nativas, sonido y ritmo narrativo para cada plataforma — sin sacrificar la calidad de la marca.",
      h5: "Los cuellos de botella típicos",
      p11: "A partir de nuestras auditorías de los últimos meses, se han cristalizado cuatro cuellos de botella recurrentes:",
      bottle1: "<strong>Muy pocas variantes de gancho.</strong> La mayoría de las marcas prueban de 2 a 3 ganchos por ola creativa. La recomendación de la plataforma sería de 6 a 10. Quienes no prueban, no saben qué gancho funciona en su nicho.",
      bottle2: "<strong>Faltan tomas de textura.</strong> Los compradores de belleza quieren ver la consistencia. Una gota de base, una textura de crema, un brillo de sérum. Estas tomas a menudo están ausentes porque son intensivas en producción. Las marcas que las tienen destacan.",
      bottle3: "<strong>Estilo UGC sin estrategia.</strong> 'Hagamos algo tipo UGC' no es una estrategia. Los creativos exitosos de estilo UGC tienen un formato de gancho claro, un tono de voz bien considerado y una hipótesis de por qué encajan en este nicho.",
      bottle4: "<strong>Sin registro de aprendizaje.</strong> A menudo, las marcas saben qué creativo ganó este mes — pero no <em>qué tipo de gancho</em> ha dominado en su nicho en los últimos 6 meses. Esta visión estratégica se desperdicia.",
      h6: "Lo que aportamos",
      p12: "No somos un estudio generalista con la belleza como nota al margen. Hemos afinado activamente nuestro enfoque en este nicho:",
      team1: "<strong>Olha</strong> viene de la fotografía de belleza y moda y conoce los requisitos de nitidez de textura, tono de piel y diseño de escenarios.",
      team2: "<strong>Denys</strong> como especialista en marketing e IA conoce las dinámicas de plataforma decisivas para los anuncios de TikTok y Meta en belleza y salud.",
      team3: "<strong>Ralph</strong> piensa en las conexiones del ciclo de vida (CRM) — qué sucede después del clic.",
      team4: "<strong>Yahya</strong> impulsa el inbound: alcance en LinkedIn con fundadores D2C, leads de rendimiento, tomadores de decisiones.",
      p13: "Esta especialización es una limitación deliberada: no aceptamos mandatos de SaaS, marcas de viajes o B2B. A cambio, sabemos dónde están las palancas en nuestro nicho.",
      h7: "Lo que puedes hacer a continuación",
      p14: "Si diriges una marca D2C en belleza, salud o estilo de vida y te preguntas si tu output creativo coincide con tu presupuesto publicitario, pregúntate tres cosas:",
      q1: "¿Has lanzado al menos 15 creativos publicitarios frescos y probados en los últimos 30 días?",
      q2: "¿Puedes explicar <strong>por qué</strong> funcionan tus tres mejores creativos — o solo <strong>que</strong> funcionan?",
      q3: "¿Hay un registro de aprendizaje documentado que te diga qué lógica de gancho ha sido más estable en tu nicho en los últimos 6 meses?",
      p15Before: "¿Tres veces no? Entonces una",
      p15Link: "llamada estratégica",
      p15After: "probablemente sea una buena inversión.",
    },
    fkh: {
      h1: "El problema con los dos extremos",
      p1: "<strong>La fotografía pura</strong> proporciona confianza, autenticidad y nitidez de textura. Pero es lenta. Un día de rodaje en una ubicación real para una sesión de belleza cuesta fácilmente entre €4k y €8k y produce quizás diez visuales finales. Con un gasto publicitario de €30k al mes, eso dura dos semanas — luego comienza la fatiga creativa.",
      p2: "<strong>La IA pura</strong> proporciona velocidad y variaciones infinitas. Pero tiene un problema de identificación: las caras de IA parecen demasiado suaves, las manos de IA tienen seis dedos, las texturas de IA se sienten predecibles. En belleza, donde los compradores leen micro-señales minúsculas, la confianza se rompe inmediatamente.",
      p3: "Cualquiera que elija uno de estos extremos debe vivir con la compensación. Quien combina ambos, no.",
      h2: "Lo que significa concretamente la producción híbrida para nosotros",
      h3a: "Nivel 1: El producto — siempre real",
      p4: "El producto nunca está solo en una escena de IA. Fotografiamos el producto real bajo condiciones controladas: temperatura de color correcta, reproducción de textura, visualización de consistencia. La postproducción trabaja con el material real — sin generación de IA del producto en sí.",
      p5: "<strong>Por qué:</strong> Los compradores esperan con razón que el producto en el anuncio corresponda al producto en la entrega. Usar IA aquí no solo es tácticamente imprudente — también puede volverse legalmente problemático bajo la ley de publicidad.",
      h3b: "Nivel 2: La persona — real, con variación de estilo",
      p6Before: "Si hay una persona en la imagen, es una persona real — no un avatar de IA. Las texturas de la piel, la pigmentación, las expresiones faciales, la postura deben ser reales, de lo contrario la identificación sufre (ver",
      p6Link: "Pilar de Beauty E-Commerce",
      p6After: ").",
      p7: "<strong>La IA entra en juego aquí para variaciones:</strong> cambiar la situación de iluminación, revisión de estilo (día cálido vs. tarde fresca), cambio de fondo, adaptación de formato. Estas variaciones no requieren un nuevo rodaje — provienen de la manipulación controlada por IA del metraje real.",
      h3c: "Nivel 3: Fondo / ambiente — la IA como palanca de producción",
      p8: "Aquí es donde reside la verdadera palanca. En lugar de alquilar una ubicación para cada variante de anuncio, generamos fondos en el ambiente deseado: baño de mármol, estudio botánico, ático urbano, paisajes de texturas hiperrealistas. El producto y la persona se integran en estos fondos — enmascarados limpiamente, con la coincidencia de luz correcta.",
      p9: "<strong>A partir de una sola sesión fotográfica real, surgen de 5 a 15 variantes de estilo</strong> para diferentes audiencias objetivo, plataformas o hipótesis — sin tener que volver a fotografiar.",
      h4: "Ley de IA de la UE: cumplimiento como ventaja, no como obstáculo",
      p10: "La Ley de IA de la UE ha estado parcialmente en vigor desde febrero de 2025; a partir de agosto de 2026, se aplica la obligación de etiquetado completo a los contenidos publicitarios generados por IA. Muchos estudios pequeños pasarán esto por alto. Nosotros lo tratamos como estándar.",
      h5a: "Lo que hacemos concretamente",
      comp1: "<strong>Convención de nombres de archivo:</strong> Cada archivo lleva una bandera de IA cuando la IA estuvo involucrada (<code>brand_creative_v3_AI-bg.jpg</code> vs. <code>brand_creative_v3_full-photo.jpg</code>).",
      comp2: "<strong>Informes para el cliente:</strong> El informe mensual documenta qué creativos contienen elementos generados por IA y en qué medida.",
      comp3: "<strong>Plantilla de briefing:</strong> Nuestro brief estándar pregunta tempranamente qué componentes de IA se desean y cuáles se excluyen.",
      comp4: "<strong>DPA con los clientes:</strong> El Acuerdo de Procesamiento de Datos (RGPD) y la cláusula de transparencia de IA son componentes estándar de nuestros contratos.",
      p11: "El efecto: cuando las primeras marcas realicen auditorías de cumplimiento de sus materiales publicitarios a partir de agosto de 2026, no hay nada que hacer. Todo está documentado, todo cumple la normativa.",
      h5b: "Clasificación de riesgo",
      p12: "Los fondos generados por IA en la publicidad entran en 'riesgo limitado' — sin certificación elaborada como la IA de alto riesgo (diagnósticos médicos, decisiones de contratación), sólo obligaciones de transparencia y etiquetado. Esta es exactamente la zona en la que trabajamos.",
      h6: "Qué herramientas usamos — y cuáles evitamos deliberadamente",
      toolsYes: "En uso:",
      tool1: "Midjourney (v6+) para fondos y variaciones de estado de ánimo",
      tool2: "Adobe Firefly para una generación legalmente segura en el entorno publicitario DACH",
      tool3: "Photoshop / Relleno Generativo de Adobe para cambios específicos en el área de la imagen",
      tool4: "Presets de Lightroom personalizados para un lenguaje visual coherente por marca",
      toolsNo: "Deliberadamente no en uso:",
      noTool1: "Herramientas de IA con orígenes de datos de entrenamiento poco claros o riesgo de infracción de derechos de autor",
      noTool2: "Generación por IA de rostros destinados a representar a personas reales",
      noTool3: "Generadores de anuncios totalmente automatizados que producen creativos sin hipótesis humana",
      p13: "No somos religiosos respecto a la elección de herramientas — somos religiosos respecto a quién es responsable de la imagen final. Esa responsabilidad es nuestra, no de un modelo.",
      h7: "Cuándo vale la pena ser híbrido",
      p14: "La producción híbrida vale la pena sobre todo en dos escenarios:",
      when1: "<strong>Mayor frecuencia:</strong> Si necesitas nuevos creativos en un ciclo de 2–4 semanas, lo híbrido es la única opción escalable sin pérdida de calidad.",
      when2: "<strong>Pruebas A/B con variantes de estilo:</strong> Si quieres saber si un fondo botánico funciona mejor que uno urbano, necesitas ambos — rápidamente, dentro de la misma familia visual. El enfoque híbrido ofrece eso.",
      p15: "Si solo necesitas un visual héroe por temporada, la fotografía clásica es más económica. Somos honestos al respecto.",
      h8: "Lo que puedes hacer a continuación",
      p16: "Si tienes una marca D2C y sientes que la producción se está convirtiendo en un cuello de botella:",
      next1: "Observa tus últimos 30 creativos de anuncios. ¿Cuántos son auténticas variantes de estilo de la misma sesión fotográfica — y cuántos son 'más de lo mismo'?",
      next2: "Pregunta a tu estudio actual: <em>¿Cómo producirían 25 creativos finales en lugar de 8 a partir de un solo día de rodaje?</em>",
      next3: "Pregúntate a ti mismo: ¿tienes una posición escrita sobre el uso de IA en la publicidad — o se decide sobre la marcha cuando llega el siguiente brief?",
      p17Before: "¿Tres veces sin un sí claro? Nos encantaría hablar.",
      p17Link: "Reserva una llamada estratégica →",
    }
