    hooks: {
      p1: "Los primeros 1,5 segundos de un anuncio creativo deciden si alguien se detiene o sigue haciendo scroll. Este momento se llama el <strong>Gancho (Hook)</strong> — y es el único elemento de tu creativo cuyo rendimiento puedes leer directamente en casi cualquier análisis de plataforma (Tasa de retención a 3 segundos, Tasa de gancho).",
      p2: "A partir de unos 200 ganchos probados en Belleza/Salud/Estilo de vida, hemos identificado siete patrones que sistemáticamente superan al resto — y tres que deberías evitar.",
      h2a: "Siete patrones de gancho que funcionan en belleza",
      h3a: "1. La Apertura de Punto de Dolor",
      p3: "Referencia directa al problema: <em>\"¿Protector solar pegajoso? Aquí está la solución.\"</em> Funciona porque desencadena una resonancia en el espectador sin ningún preámbulo. Especialmente efectivo en TikTok, donde la capacidad de atención es más corta que en Instagram.",
      h3b: "2. La Parada de Textura",
      p4: "Toma macro de una textura de crema, una gota de base de maquillaje, un brillo de sérum. Estático o con movimiento mínimo. Funciona porque los compradores de belleza están visualmente calibrados para las texturas y el ojo se enfoca automáticamente.",
      h3c: "3. La Declaración Contraintuitiva",
      p5: "<em>\"Nunca me lavo la cara con agua.\"</em> Rompiendo una rutina esperada. Crea disonancia cognitiva — y con ella el deseo de descubrir por qué.",
      h3d: "4. El Inicio en Medio de la Rutina (Voice-Over)",
      p6: "La voz en off comienza a mitad de frase, como si el vídeo ya hubiera empezado. Imita el patrón nativo de TikTok y previene el sentimiento de \"esto es un anuncio\" en el primer segundo.",
      h3e: "5. El Encuadre Antes-Después",
      p7: "Un clásico que nunca muere — siempre y cuando el encuadre del antes sea honesto. Funciona en cuidado de la piel, cabello, maquillaje. <strong>Nota de cumplimiento:</strong> En la región DACH solo con un etiquetado claro de antes/después y sin declaraciones de eficacia no permitidas.",
      h3f: "6. La Declaración de Números",
      p8: "<em>\"98% menos de enrojecimiento de la piel después de 14 días.\"</em> Los números concretos funcionan — cuando son verificables. Los números vagos crean escepticismo y son contraproducentes.",
      h3g: "7. El Consejo Privilegiado (Insider Tip)",
      p9: "<em>\"Lo que los dermatólogos dicen sobre la niacinamida que el mundo del marketing no sabe.\"</em> Apela al deseo de conocimiento interno. Requiere contenido genuino de expertos detrás de él, de lo contrario la tasa de abandono después del quinto segundo es brutal.",
      h2b: "Tres ganchos que deberías evitar",
      h3h: "1. Apertura fría de estilo de vida genérico",
      p10: "Amanecer, mujer sonriente en la playa, logotipo. Esa es la estética de 2018 — y en su mayoría tiene un rendimiento inferior en paid social hoy. Nada sucede en los primeros 3 segundos que detenga el pulgar.",
      h3i: "2. Apertura \"Hola, soy [Nombre]\"",
      p11: "Lo que funciona para los creadores de UGC en YouTube fracasa en paid social. Los primeros segundos son demasiado valiosos para desperdiciarlos en una introducción. La identificación puede venir después.",
      h3j: "3. Animación de logotipo primero",
      p12: "Un logotipo animado al principio señala: \"Anuncio\". Resultado: saltar (skip). Los logotipos van al final, no al principio.",
      h2c: "Cómo probar ganchos sistemáticamente",
      p13Pre: "El mayor error: tres ganchos diferentes para tres creativos diferentes. Entonces no sabes si fue el gancho o el cuerpo. <strong>Mantén constante el cuerpo, varía solo el gancho.</strong> Por gancho invierte entre €2,000–5,000 para probar, luego evalúa. Más sobre esto en nuestro",
      p13Link: "Creative Engine",
      p13After: ".",
    },
    fatigue: {
      p1: "La fatiga creativa no se reconoce en una sesión de brainstorming. Se reconoce en los datos — y antes de lo que la mayoría de las marcas mira. Aquí están los cuatro indicadores de alerta temprana que monitoreamos diariamente, más la regla de parada que nos protege de gastos publicitarios innecesarios.",
      h2a: "1. La tasa de gancho (hook rate) cae primero",
      p2: "La Tasa de Gancho (Tasa de retención a 3 segundos) es la señal de advertencia temprana más honesta. Mide cuántas personas se detienen en absoluto — antes de que cada píxel posterior juegue un papel. Si tu tasa de gancho cae más de un 15% durante 7 días sin que la audiencia o la ubicación cambien, el creativo está fatigado. El CTR y el ROAS suelen seguir 4–10 días después.",
      p3: "<strong>Lo que debes hacer:</strong> no esperes hasta que el ROAS colapse. Prepara el reemplazo ya cuando la tasa de gancho empiece a disminuir.",
      h2b: "2. El CPM sube sin que la segmentación lo explique",
      p4: "Cuando tu CPM sube más de un 20% a pesar de que la audiencia, la ubicación y la puja siguen siendo las mismas, el algoritmo puede ver que tu creativo está fatigado. Las plataformas aumentan el precio por el material fatigado porque ofrece menos interacción.",
      p5: "<strong>Lo que debes hacer:</strong> compara el CPM con el rango de los 30 días anteriores. Si sube de forma desproporcionada, comprueba la tasa de gancho al mismo tiempo.",
      h2c: "3. La frecuencia supera el 3.5",
      p6: "Con una Frecuencia > 3.5 (en 7 días) la misma persona ve tu creativo más de tres veces. En Belleza/Salud este es el umbral de dolor típico a partir del cual el engagement y el CTR caen rápidamente.",
      p7: "<strong>Lo que debes hacer:</strong> monitorea la frecuencia directamente en el Administrador de Anuncios de Meta. Los límites de frecuencia ayudan — pero no sustituyen a creativos frescos.",
      h2d: "4. El CTR cae pero la tasa de conversión se mantiene estable",
      p8: "Este es el indicador más sutil: menos clics, pero los que llegan convierten. Lo que a primera vista parece un \"deterioro de audiencia\" suele ser fatiga creativa: sólo los genuinamente interesados siguen convencidos por el viejo creativo — los navegantes casuales no. Resultado: los volúmenes absolutos caen, el embudo parece artificialmente \"más limpio\".",
      p9: "<strong>Lo que debes hacer:</strong> lee la tendencia de volumen en lugar de la tendencia de ratio. Menos clics con la misma tasa de conversión = techo de escala.",
      h2e: "La regla de parada",
      p10: "Retiramos un creativo de circulación cuando <strong>dos de los cuatro</strong> indicadores han estado fuera de tolerancia durante 7 días. No sólo al llegar a tres. No sólo cuando baja el ROAS.",
      p11Pre: "Esto suena estricto, pero es económicamente correcto: para cuando el ROAS cae, a menudo ya has quemado un 20–40% de gasto innecesario en un creativo que se fatiga. El pipeline de los siguientes creativos debe estar preparado de antemano — ver",
      p11Link: "Creative Engine",
      p11After: ".",
      h2f: "Lo que NO es la fatiga creativa",
      p12: "Importante: fatiga creativa no es \"el creativo está empeorando\". El creativo es el mismo. Lo que cambia es la proporción de <em>personas que aún no lo han visto</em> frente a <em>personas que lo ven por tercera vez</em>. Cada paso de escalado acelera este proceso.",
      p13: "La consecuencia: escalar requiere pipeline. Sin creativos nuevos de forma continua, escalar es matemáticamente imposible.",
    },
    hypo: {
      p1: "\"Probemos algo nuevo\" no es una hipótesis. Es un deseo. Una verdadera hipótesis creativa tiene tres componentes que convierten cada prueba de un intento aleatorio a una pregunta controlada.",
      h2a: "Los tres componentes",
      h3a: "1. La variable (qué cambiamos)",
      p2: "Concreta y aislada. <em>\"Probamos el Gancho A contra el Gancho B.\"</em> No <em>\"Probamos la variante 3 contra la variante 7.\"</em> Si la variante 3 y 7 difieren en cinco cosas, no aprendes nada.",
      h3b: "2. La expectativa (qué KPI cambia y cómo)",
      p3: "Necesitas saber antes de la prueba qué KPI debería cambiar y cómo. De lo contrario, buscarás el KPI que se vea mejor después de la prueba — y eso es autoconfirmación, no aprendizaje.",
      h3c: "3. La justificación (por qué sospechamos esto)",
      p4: "A partir de datos de tus propias campañas, de la observación del mercado, del análisis de competidores. Una buena justificación conecta la hipótesis con algo que ya sabes.",
      h2b: "La plantilla",
      p5: "Usamos este formato internamente para cada ola de pruebas:",
      bq1: "Sospechamos que <strong>[variante concreta]</strong> para <strong>[público objetivo / audiencia concreta]</strong> conducirá a <strong>[efecto KPI con delta esperado]</strong> — porque <strong>[justificación basada en evidencia]</strong>.",
      h2c: "Tres ejemplos de la práctica",
      h3d: "Ejemplo 1 — Variante de gancho",
      bq2: "Sospechamos que una variante de gancho con el punto de dolor \"protector solar pegajoso\" para la audiencia \"mujeres afines al cuidado de la piel 25–40, urbanas\" conducirá a una tasa de gancho al menos un 25% mayor — porque las 3 principales publicaciones orgánicas de nuestros competidores en TikTok utilizan la misma apertura de punto de dolor.",
      h3e: "Ejemplo 2 — Variante de formato",
      bq3: "Sospechamos que un formato vertical de 9:16 frente a un cuadrado de 4:5 en el feed de TikTok logrará una tasa de retención al menos un 15% mayor — porque el formato 9:16 llena de forma nativa la pantalla de TikTok y reduce el \"reconocimiento de anuncio\".",
      h3f: "Ejemplo 3 — Postproducción",
      bq4: "Sospechamos que una postproducción desaturada y de mayor contraste frente al actual lenguaje visual cálido conducirá a un CPC un 10% menor — porque la competencia está trabajando mucho con un tono cálido-cinematográfico este trimestre y nuestros creativos destacarían por contraste.",
      h2d: "Qué hace a una mala hipótesis",
      bad1: "<strong>Demasiado vaga:</strong> \"Aparentemos más modernos.\" (¿Qué es \"moderno\"? ¿Qué KPI?)",
      bad2: "<strong>Demasiadas variables:</strong> \"Cambiemos el gancho, el cuerpo y el CTA al mismo tiempo.\" (Tasa de aprendizaje = cero)",
      bad3: "<strong>Sin justificación:</strong> \"Creo que vertical es mejor.\" (Creer no es probar)",
      bad4: "<strong>No falsable:</strong> \"Rendirá mejor.\" (¿Qué es \"mejor\"?)",
      h2e: "¿Cuántas hipótesis por ciclo?",
      p6: "En nuestras igualas (retainers) típicamente formulamos 3–5 hipótesis por ciclo de producción. Más es operativamente difícil de probar (las celdas de prueba necesitan estadística). Menos deja oportunidades de aprendizaje sobre la mesa.",
      p7Pre: "Cada hipótesis aterriza en el",
      p7Link: "Learning Log",
      p7After: " — antes de la prueba, con la configuración, y después de la prueba con el resultado. De esta manera, a lo largo de trimestres, se acumula un cuerpo de conocimiento incalculable.",
    },
    learning: {
      p1: "La mayoría de las marcas saben qué creativo ganó este mes. Pocas saben <em>qué tipo de gancho</em> domina de manera consistente en su nicho a lo largo de 12 meses. El registro de aprendizaje (learning log) cierra esta brecha — es una de las herramientas más subestimadas en el performance creative.",
      h2a: "Por qué la mayoría de las marcas no tienen uno",
      p2: "Tres razones: la prueba ha terminado, la presión pasa al mes siguiente, nadie lo anota. El informe de la plataforma está ahí, pero resume resultados — no insights. Un insight es <em>generalizable</em>; un resultado depende del contexto.",
      h2b: "Los campos requeridos por entrada",
      field1: "<strong>Fecha + ID de Prueba</strong> — referencia única para que puedas reconstruir las pruebas más tarde.",
      field2Pre: "<strong>Hipótesis (formulada antes de la prueba)</strong> — ver",
      field2Link: "Hipótesis Creativas",
      field2After: ".",
      field3: "<strong>Configuración de la prueba</strong> — audiencia, ubicación, presupuesto por celda, regla de parada, plataforma.",
      field4: "<strong>Resultado (Delta KPI entre celdas)</strong> — tasa de gancho, CTR, CPC, ROAS, cada métrica relevante.",
      field5: "<strong>Verificación</strong> — ¿Se alcanzó significación estadística? Con pruebas pequeñas a menudo es difícil — entonces una declaración de confianza suave es suficiente.",
      field6: "<strong>Insight generalizable</strong> — la entrada más importante. ¿Qué aprendemos sobre los tipos de ganchos, formatos o mundos visuales en nuestro nicho?",
      field7: "<strong>Próxima prueba</strong> — lo que queremos examinar a continuación en base a este resultado.",
      h2c: "Ejemplo de entrada",
      bq1: "<strong>Prueba #14 · 2026-04-22</strong><br>Hipótesis: La variante de gancho \"¿protector solar pegajoso?\" frente a la variante aspiracional actual lidera a una tasa de gancho al menos un 25% mayor.<br>Configuración: In-Feed de TikTok, audiencia \"Skincare 25–40 DACH\", €2,500 por celda, parada después de 5 días.<br>Resultado: Tasa de gancho +32%, CTR +18%, CPC −12%, ROAS +9%.<br>Verificación: 6,800 clics por celda, p ≪ 0.01.<br>Insight generalizable: Los ganchos de puntos de dolor concretos-físicos superan a la aspiración emocional-abstracta en el segmento DACH de cuidado solar. Probablemente transferible a otras categorías de dolor sensorial (pegajoso, grasoso, pesado).<br>Próxima prueba: transferir el gancho de punto de dolor a la línea anti-edad — prueba la suposición de transferibilidad.",
      h2d: "Herramientas que usamos",
      p3: "Trabajamos con bases de datos de Notion (internas + compartidas con clientes). Una tabla con los campos de arriba como columnas es suficiente. Más importante que la herramienta es la disciplina: cada prueba entra en el registro, sin excepciones, dentro de las 48 horas posteriores a su finalización.",
      p4: "Herramientas alternativas: Airtable, Google Sheets con una estructura clara, tareas de Linear con una etiqueta de prueba.",
      h2e: "Lo que pasa después de 12 meses",
      p5: "Después de un año tienes de 30 a 60 entradas. Cuando buscas en los insights generalizables, ves patrones: ¿qué tipos de ganchos funcionan repetidamente en tu nicho? ¿Qué formatos son estables? ¿Qué estilos de postproducción envejecen mejor?",
      p6: "Este es el momento en que tu conocimiento de marketing <em>se compone</em> (compounds). Con cada nueva campaña ya no empiezas desde cero. Empiezas desde el 47% de ganchos que han rendido mejor en tu nicho en el pasado — y entonces solo haces las preguntas abiertas.",
      p7: "Este es el verdadero valor de un retainer de performance creative más allá de los primeros 6 meses: no los creativos individuales, sino la ruta de aprendizaje acumulada.",
    },
    d2c: {
      p1: "El D2C de belleza en la región DACH se encuentra en un umbral en 2026. Lo que funcionaba hace dos años hoy funciona — parcialmente — y lo que funcionará el año que viene apenas está emergiendo. Aquí están los cinco cambios que estamos viendo actualmente.",
      h2a: "1. TikTok Shop se convierte en un canal, no en una novedad",
      p2: "Lo que todavía era un campo experimental en 2024 es un canal de ventas independiente en 2026. TikTok Shop aceleró su lanzamiento en DACH en 2025; las marcas D2C de belleza que llegan temprano están construyendo un alcance orgánico que complementa — no reemplaza — a la adquisición pagada.",
      p3: "<strong>Qué significa esto:</strong> los creativos deben pensar en una lógica \"shoppable\" (comprable). Gancho directo, corte de producto claro, secuencia de demostración corta, sonido verificado. Los videos puramente de storytelling de marca rinden significativamente peor aquí que en Instagram.",
      h2b: "2. Aumenta la presión del cumplimiento: HWG, Reglamento de Cosméticos, Ley de IA de la UE",
      p4: "Tres marcos regulatorios se están endureciendo simultáneamente:",
      comp1: "<strong>HWG (Heilmittelwerbegesetz)</strong> — las declaraciones de eficacia se están analizando de forma más estricta, y las oleadas de cartas de cese y desistimiento para marcas de belleza de \"tendencia médica\" están aumentando.",
      comp2: "<strong>Reglamento de Cosméticos 1223/2009</strong> — las declaraciones de ingredientes deben estar documentadas; las infracciones son cada vez más perseguidas por los competidores en la región DACH.",
      comp3Pre: "<strong>Ley de IA de la UE a partir de agosto de 2026</strong> — el contenido publicitario generado por IA debe ser etiquetado. Más en nuestro",
      comp3Link: "Clúster sobre la Ley de IA de la UE",
      comp3After: ".",
      p5: "<strong>Qué significa esto:</strong> el cumplimiento ya no es algo que se piensa a posteriori. Las marcas que ignoran esto corren riesgos no solo de consecuencias legales, sino también de desmonetización en las plataformas y daño a la confianza con sus propios clientes.",
      h2c: "3. La visibilidad de la IA cambia el customer journey",
      p6: "Los compradores investigan cada vez más los productos de belleza en asistentes de búsqueda impulsados por IA — ChatGPT, Perplexity, Gemini, Google AI Overviews. Los que no son citados allí están perdiendo una parte creciente de la fase de descubrimiento.",
      p7: "<strong>Qué significa esto:</strong> el AEO (Answer Engine Optimization) complementa al SEO clásico. Datos estructurados, contenido claro de preguntas y respuestas (Q&A), explicaciones de ingredientes con fuentes, se convierten en bloques de construcción obligatorios.",
      h2d: "4. Retención antes que adquisición — el péndulo oscila de nuevo",
      p8: "La ola de D2C de 2018–2022 vivió de la adquisición: muchos nuevos clientes, muchas primeras compras. En 2026, el péndulo ha vuelto a oscilar. Los CACs han subido significativamente, los márgenes de primera compra se reducen. Las marcas que están creciendo son las que organizan sistemáticamente segundas y terceras compras — a través de correo electrónico, suscripciones, programas de lealtad.",
      p9: "<strong>Qué significa esto:</strong> el performance creative ya no es solo una herramienta de adquisición. También debe producir creativos de re-engagement (reactivación) y lealtad — con su propia hipótesis y lógica de prueba.",
      h2e: "5. Lo aspiracional ha muerto — la identificación toma el control",
      p10: "El mayor cambio estético: los compradores de belleza ya no se identifican con modelos inalcanzables, sino con personas que se parecen a ellos. Tonos de piel, grupos de edad, imperfecciones, rutinas reales. Esto comenzó en 2024 y es el estándar en 2026.",
      p11: "<strong>Qué significa esto:</strong> el casting se vuelve más importante que el presupuesto de producción. Una textura de piel real en una producción de €1,500 supera a una foto glamurosa retocada en una producción de €15,000 — cuando encaja con la audiencia.",
      h2f: "Lo que hace Mirrou con esto",
      p12Pre: "Estamos construyendo nuestra oferta alrededor de estos cambios: especialización en belleza, una mentalidad de \"compliance-first\", producción híbrida con IA, conexión con el ciclo de vida a través de la experiencia CRM de Ralph, y creativos fuertes en identificación en lugar de puro glamour. Dirección Creativa: Olha Yevtushenko. Más en nuestro",
      p12Link: "Pilar de Beauty E-Commerce",
      p12After: ".",
    },
    aiact: {
      p1: "A partir de agosto de 2026, el contenido publicitario generado por IA en la UE deberá estar etiquetado. Lo que suena a ruido burocrático es en realidad un cambio sustancial — y para los equipos de marketing que utilizan herramientas de IA (que son casi todos), una tarea de preparación concreta.",
      h2a: "Lo que la Ley de IA de la UE regula concretamente para la publicidad",
      p2: "La Ley de IA de la UE distingue cuatro clases de riesgo. Las aplicaciones de marketing caen prácticamente siempre bajo <strong>\"riesgo limitado\"</strong>: no hay certificación compleja, pero sí obligaciones de transparencia y etiquetado.",
      p3: "Concretamente, esto significa a partir de agosto de 2026:",
      rule1: "<strong>Obligación de etiquetado para contenido generado por IA.</strong> Las imágenes, videos y audios que fueron generados total o sustancialmente por IA deben ser reconocibles como tales.",
      rule2: "<strong>Etiquetado de Deepfakes.</strong> Las personas creadas sintéticamente o las personas reales manipuladas deben ser etiquetadas explícitamente como artificiales.",
      rule3: "<strong>Obligación de alfabetización en IA (AI literacy).</strong> En vigor desde febrero de 2025: las empresas deben asegurarse de que los empleados que utilizan herramientas de IA tengan la competencia suficiente.",
      h2b: "Qué cuenta como \"generado por IA\"",
      p4: "Esta es la pregunta más delicada. La Comisión de la UE aún no ha publicado una definición detallada final, pero la interpretación actual se lee más o menos así:",
      class1: "<strong>Totalmente generado por IA:</strong> imagen, video o audio creado sin material de origen humano (por ejemplo, un fondo de Midjourney desde cero). Se requiere etiquetado claro.",
      class2: "<strong>Sustancialmente editado por IA:</strong> material real donde la IA ha cambiado algo más que elementos marginales (intercambio de personas, intercambio de fondo, transferencia de estilo). Etiquetado recomendado / requerido.",
      class3: "<strong>Edición asistida por IA:</strong> uso de herramientas como el Relleno Generativo para pequeñas correcciones, ampliación con IA (upscaling), enmascaramiento asistido por IA. <em>Probablemente</em> no sea obligatorio el etiquetado — la regulación detallada aún está pendiente.",
      p5: "<strong>Recomendación práctica:</strong> ante la duda, etiqueta. Cumplir en exceso (Over-compliance) es más barato que no cumplir.",
      h2c: "Cómo puede verse el etiquetado",
      p6: "La forma concreta aún no se ha finalizado, pero los siguientes patrones probablemente serán aceptados:",
      label1: "Aviso visible en la imagen/video: \"Asistido por IA\", \"Generado por IA\", o un símbolo",
      label2: "Metadatos legibles por máquina (estándar C2PA, Content Credentials)",
      label3: "Etiquetas nativas de IA de las plataformas (Meta ya las tiene, TikTok también)",
      p7: "Recomendamos combinar los tres: aviso visible en el visual + Content Credentials en los metadatos + etiquetas de la plataforma donde estén disponibles.",
      h2d: "Qué ocurre en caso de incumplimiento",
      p8: "Multas de hasta 15 millones de euros o el 3% del volumen de negocios anual mundial (lo que sea mayor) por violaciones de las obligaciones de transparencia. En la práctica: las demandas de competidores y de protección al consumidor probablemente serán el mecanismo de cumplimiento más frecuente que las propias autoridades.",
      p9: "Realista para una marca D2C de belleza: cartas de cese y desistimiento, desmonetización por parte de las plataformas, daño a la reputación. La desmonetización de las plataformas en particular es peligrosa — Meta y TikTok aplicarán sus propias verificaciones de cumplimiento de manera preventiva.",
      h2e: "Lo que Mirrou hace — como estándar, no como añadido",
      p10: "No tratamos el etiquetado como una reacción, sino como una parte integral de la producción:",
      action1: "Convención de nombres de archivo con bandera de IA",
      action2: "Informe mensual para clientes con resumen de cuota de IA",
      action3: "Plantilla de briefing con pregunta de permiso para IA",
      action4: "DPA (RGPD) y cláusula de transparencia de IA en el contrato estándar",
      action5: "Generación de metadatos C2PA para los assets entregados",
      p11Pre: "Más detalles en nuestro",
      p11Link: "Pilar Foto + IA",
      p11After: ".",
      h2f: "Lo que tú como marca deberías hacer ahora",
      todo1: "<strong>Audita tu inventario creativo actual.</strong> ¿Qué visuales contienen componentes de IA? ¿Están documentados?",
      todo2: "<strong>Actualiza tu plantilla de briefing.</strong> Añade los componentes de IA como una pregunta explícita.",
      todo3: "<strong>Verifica a tus socios contractuales.</strong> Habla con estudios externos y freelancers sobre su práctica de cumplimiento de la IA.",
      todo4: "<strong>Usa las etiquetas de las plataformas.</strong> Meta y TikTok ofrecen etiquetas para IA. Úsalas activamente en lugar de ignorarlas.",
      p12: "Quienes comiencen con un cumplimiento limpio en agosto de 2026 tendrán una ventaja sobre las marcas que tengan que pasar al modo reactivo — y esa será la mayoría.",
    }
